import { combineReducers } from 'redux';
import {
  SETUP_OCR_ADMIN,
  SETUP_OCR_ADMIN_CLIENT,
  SETUP_OCR_CLIENT,
  SETUP_OCR_USER,
  SETUP_OCR_JWTS,
  SETUP_OCR_TOKENS,
  SETUP_OCR_CATALOG_ATTRIBUTES_REQUEST,
  SETUP_OCR_CATALOG_ATTRIBUTES_SUCCESS,
  SETUP_OCR_CATALOG_ATTRIBUTES_FAILURE,
  SETUP_OCR_CLIENT_COLORS_REQUEST,
  SETUP_OCR_CLIENT_COLORS_SUCCESS,
  SETUP_OCR_CLIENT_COLORS_FAILURE,
  SETUP_OCR_PROMO_TYPES_REQUEST,
  SETUP_OCR_PROMO_TYPES_SUCCESS,
  SETUP_OCR_PROMO_TYPES_FAILURE,
  SETUP_OCR_SUBSCRIPTIONS_REQUEST,
  SETUP_OCR_SUBSCRIPTIONS_SUCCESS,
  SETUP_OCR_SUBSCRIPTIONS_FAILURE,
} from 'actions/Types'
import isEmpty from 'lodash/isEmpty'
import {createRequestReducer} from './CustomReducer'
import appReducer from 'store'

export const setupLoginInfo = {

}

export const setupOcrCatalog = createRequestReducer({
  FETCH_REQUEST: SETUP_OCR_CATALOG_ATTRIBUTES_REQUEST,
  FETCH_SUCCESS: SETUP_OCR_CATALOG_ATTRIBUTES_SUCCESS,
  FETCH_FAILURE: SETUP_OCR_CATALOG_ATTRIBUTES_FAILURE,
  initialState: []
});

export const setupOcrClientColors = createRequestReducer({
  FETCH_REQUEST: SETUP_OCR_CLIENT_COLORS_REQUEST,
  FETCH_SUCCESS: SETUP_OCR_CLIENT_COLORS_SUCCESS,
  FETCH_FAILURE: SETUP_OCR_CLIENT_COLORS_FAILURE,
  initialState: []
});

export const setupOcrPromoTypes = createRequestReducer({
  FETCH_REQUEST: SETUP_OCR_PROMO_TYPES_REQUEST,
  FETCH_SUCCESS: SETUP_OCR_PROMO_TYPES_SUCCESS,
  FETCH_FAILURE: SETUP_OCR_PROMO_TYPES_FAILURE,
  initialState: []
});

export const setupOcrSubscriptions = createRequestReducer({
  FETCH_REQUEST: SETUP_OCR_SUBSCRIPTIONS_REQUEST,
  FETCH_SUCCESS: SETUP_OCR_SUBSCRIPTIONS_SUCCESS,
  FETCH_FAILURE: SETUP_OCR_SUBSCRIPTIONS_FAILURE,
  initialState: []
});

const generalStorage = combineReducers({
  setupOcrCatalog,
  setupOcrClientColors,
  setupOcrPromoTypes,
  setupOcrSubscriptions,
});

export default generalStorage;
